//    Copyright 2019 Google Inc.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        https://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file proto/google/fhir/proto/r4/core/resources/schedule.proto (package google.fhir.r4.core, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Any } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any } from "@bufbuild/protobuf/wkt";
import { file_proto_google_fhir_proto_annotations } from "../../../annotations_pb";
import type { Boolean, Code, CodeableConcept, Extension, Id, Identifier, Meta, Narrative, Period, Reference, String, Uri } from "../datatypes_pb";
import { file_proto_google_fhir_proto_r4_core_datatypes } from "../datatypes_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/google/fhir/proto/r4/core/resources/schedule.proto.
 */
export const file_proto_google_fhir_proto_r4_core_resources_schedule: GenFile = /*@__PURE__*/
  fileDesc("Cjhwcm90by9nb29nbGUvZmhpci9wcm90by9yNC9jb3JlL3Jlc291cmNlcy9zY2hlZHVsZS5wcm90bxITZ29vZ2xlLmZoaXIucjQuY29yZSLvBwoIU2NoZWR1bGUSIwoCaWQYASABKAsyFy5nb29nbGUuZmhpci5yNC5jb3JlLklkEicKBG1ldGEYAiABKAsyGS5nb29nbGUuZmhpci5yNC5jb3JlLk1ldGESMAoOaW1wbGljaXRfcnVsZXMYAyABKAsyGC5nb29nbGUuZmhpci5yNC5jb3JlLlVyaRIrCghsYW5ndWFnZRgEIAEoCzIZLmdvb2dsZS5maGlyLnI0LmNvcmUuQ29kZRIsCgR0ZXh0GAUgASgLMh4uZ29vZ2xlLmZoaXIucjQuY29yZS5OYXJyYXRpdmUSJwoJY29udGFpbmVkGAYgAygLMhQuZ29vZ2xlLnByb3RvYnVmLkFueRIxCglleHRlbnNpb24YCCADKAsyHi5nb29nbGUuZmhpci5yNC5jb3JlLkV4dGVuc2lvbhI6ChJtb2RpZmllcl9leHRlbnNpb24YCSADKAsyHi5nb29nbGUuZmhpci5yNC5jb3JlLkV4dGVuc2lvbhIzCgppZGVudGlmaWVyGAogAygLMh8uZ29vZ2xlLmZoaXIucjQuY29yZS5JZGVudGlmaWVyEiwKBmFjdGl2ZRgLIAEoCzIcLmdvb2dsZS5maGlyLnI0LmNvcmUuQm9vbGVhbhI+ChBzZXJ2aWNlX2NhdGVnb3J5GAwgAygLMiQuZ29vZ2xlLmZoaXIucjQuY29yZS5Db2RlYWJsZUNvbmNlcHQSOgoMc2VydmljZV90eXBlGA0gAygLMiQuZ29vZ2xlLmZoaXIucjQuY29yZS5Db2RlYWJsZUNvbmNlcHQSNwoJc3BlY2lhbHR5GA4gAygLMiQuZ29vZ2xlLmZoaXIucjQuY29yZS5Db2RlYWJsZUNvbmNlcHQSrgEKBWFjdG9yGA8gAygLMh4uZ29vZ2xlLmZoaXIucjQuY29yZS5SZWZlcmVuY2VCf/DQh+sEAfL//MIGB1BhdGllbnTy//zCBgxQcmFjdGl0aW9uZXLy//zCBhBQcmFjdGl0aW9uZXJSb2xl8v/8wgYNUmVsYXRlZFBlcnNvbvL//MIGBkRldmljZfL//MIGEUhlYWx0aGNhcmVTZXJ2aWNl8v/8wgYITG9jYXRpb24SNQoQcGxhbm5pbmdfaG9yaXpvbhgQIAEoCzIbLmdvb2dsZS5maGlyLnI0LmNvcmUuUGVyaW9kEiwKB2NvbW1lbnQYESABKAsyGy5nb29nbGUuZmhpci5yNC5jb3JlLlN0cmluZzo8wJ/jtgUDsv7klwYwaHR0cDovL2hsNy5vcmcvZmhpci9TdHJ1Y3R1cmVEZWZpbml0aW9uL1NjaGVkdWxlSgQIBxAIQngKF2NvbS5nb29nbGUuZmhpci5yNC5jb3JlUAFaVWdpdGh1Yi5jb20vZ29vZ2xlL2ZoaXIvZ28vcHJvdG8vZ29vZ2xlL2ZoaXIvcHJvdG8vcjQvY29yZS9yZXNvdXJjZXMvc2NoZWR1bGVfZ29fcHJvdG+YxrC1BwRiBnByb3RvMw", [file_google_protobuf_any, file_proto_google_fhir_proto_annotations, file_proto_google_fhir_proto_r4_core_datatypes]);

/**
 * Auto-generated from StructureDefinition for Schedule.
 * A container for slots of time that may be available for booking appointments.
 * See http://hl7.org/fhir/StructureDefinition/Schedule
 *
 * @generated from message google.fhir.r4.core.Schedule
 */
export type Schedule = Message<"google.fhir.r4.core.Schedule"> & {
  /**
   * Logical id of this artifact
   *
   * @generated from field: google.fhir.r4.core.Id id = 1;
   */
  id?: Id;

  /**
   * Metadata about the resource
   *
   * @generated from field: google.fhir.r4.core.Meta meta = 2;
   */
  meta?: Meta;

  /**
   * A set of rules under which this content was created
   *
   * @generated from field: google.fhir.r4.core.Uri implicit_rules = 3;
   */
  implicitRules?: Uri;

  /**
   * Language of the resource content
   *
   * @generated from field: google.fhir.r4.core.Code language = 4;
   */
  language?: Code;

  /**
   * Text summary of the resource, for human interpretation
   *
   * @generated from field: google.fhir.r4.core.Narrative text = 5;
   */
  text?: Narrative;

  /**
   * Contained, inline Resources
   *
   * @generated from field: repeated google.protobuf.Any contained = 6;
   */
  contained: Any[];

  /**
   * Additional content defined by implementations
   *
   * @generated from field: repeated google.fhir.r4.core.Extension extension = 8;
   */
  extension: Extension[];

  /**
   * Extensions that cannot be ignored
   *
   * @generated from field: repeated google.fhir.r4.core.Extension modifier_extension = 9;
   */
  modifierExtension: Extension[];

  /**
   * External Ids for this item
   *
   * @generated from field: repeated google.fhir.r4.core.Identifier identifier = 10;
   */
  identifier: Identifier[];

  /**
   * Whether this schedule is in active use
   *
   * @generated from field: google.fhir.r4.core.Boolean active = 11;
   */
  active?: Boolean;

  /**
   * High-level category
   *
   * @generated from field: repeated google.fhir.r4.core.CodeableConcept service_category = 12;
   */
  serviceCategory: CodeableConcept[];

  /**
   * Specific service
   *
   * @generated from field: repeated google.fhir.r4.core.CodeableConcept service_type = 13;
   */
  serviceType: CodeableConcept[];

  /**
   * Type of specialty needed
   *
   * @generated from field: repeated google.fhir.r4.core.CodeableConcept specialty = 14;
   */
  specialty: CodeableConcept[];

  /**
   * Resource(s) that availability information is being provided for
   *
   * @generated from field: repeated google.fhir.r4.core.Reference actor = 15;
   */
  actor: Reference[];

  /**
   * Period of time covered by schedule
   *
   * @generated from field: google.fhir.r4.core.Period planning_horizon = 16;
   */
  planningHorizon?: Period;

  /**
   * Comments on availability
   *
   * @generated from field: google.fhir.r4.core.String comment = 17;
   */
  comment?: String;
};

/**
 * Describes the message google.fhir.r4.core.Schedule.
 * Use `create(ScheduleSchema)` to create a new message.
 */
export const ScheduleSchema: GenMessage<Schedule> = /*@__PURE__*/
  messageDesc(file_proto_google_fhir_proto_r4_core_resources_schedule, 0);

